# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rocket Pool Improvement Proposals
description: >-
  Rocket Pool Improvement Proposals (RPIPs) describe standards for the Rocket Pool
  platform, including core protocol specifications, client APIs, and contract
  standards.
url: "https://rpips.rocketpool.net"
github_username:  rocket-pool
repository: https://github.com/rocket-pool/RPIPs/

header_pages:
 - all.html
 - tokenomics-2024.html
 - proposed.html
 - active.html
 - by_type.html
 - about_rpips.html

# Build settings
highlighter: rouge
markdown: GFM
theme: minima
kramdown:
  input: GFM
  parse_block_html: false
  # This is the default, but be explicit as some RPIPs depend on it
  auto_ids: true
  # This is to ensure more determistic behaviour
  auto_id_stripping: true
  syntax_highlighter: rouge
  gfm_quirks: [paragraph_end]

permalink: /:slug

defaults:
  -
    scope:
      path: "RPIPs"
    values:
      layout: "rpip"

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - rpip-template.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
